### ISSUE TITLE
[Suggestion] Add percentage option to number of customers per day

### ISSUE THREAD

**Issue by SSyl** [WillWilli/PlateUpEnhancementMod#1]
First off, awesome job getting BepInEx running with PlateUp! It's something that I looked into, but my only experience with BepInEx is with Valheim, and with no other mods or examples for PlateUp it felt a little daunting to undertake by myself. You should throw this up on [NexusMods.com](https://www.nexusmods.com) and you might even get a little modding community started for this game.

Anyway, to the point of my suggestion, I often find myself wishing I could relax a bit more and play longer sessions with a restaurant, but most of my games end between overtime day 5 and 10.

I think it would be awesome if you could add an option to set a percentage or multiplier that can decrease or increase the amount of customers you get per day. The game does already using certain cards (like carrot soup adds a -15% multiplier).

For example, if I could set it so there's always 50% less customers it would be nice.

I have other suggestions as well (such as the ability to restart the day without having to do a full quit of the game), but I don't want to bombard you right away.

Thanks again for this mod. Really excited to see where it goes.

**Comment by WillWilli** [comment]
Thanks for the kind feedback :) 
I did actually use several Valheim resources when figuring it all out.

You are in luck, the next feature I am currently working on is the ability to modify the number of customers per day. It should be available in the next release. 

Yeah I might stick it on NexusMods. Not sure how far the modding scene will go as I think the PlateUp dev has said Steam workshop support might be coming at some point, so that might make BepInEx redundant. Anyway, I am still working on it for now...

**Comment by WillWilli** [comment]
This is now in v0.2.0
